version: '3.9'

services:
  dishesdb:
    image: postgres:14
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dishes
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./scripts/01_init_dishes.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10